service: sls-flask

frameworkVersion: '2 || 3'

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.8
  region: ap-northeast-2

  environment:
    MONGO_HOST: ${file(./config.${opt:stage, 'dev'}.json):MONGO_HOST}
    MONGO_USER: ${file(./config.${opt:stage, 'dev'}.json):MONGO_USER}
    MONGO_PASSWORD: ${file(./config.${opt:stage, 'dev'}.json):MONGO_PASSWORD}
    MONGO_NAME: ${file(./config.${opt:stage, 'dev'}.json):MONGO_NAME}

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-wsgi
  - serverless-python-requirements
